# Generated by Django 4.2.5 on 2023-09-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_alter_course_year_alter_faculty_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.CharField(choices=[('Btech', 'Btech'), ('Mtech', 'Mtech')], default='btech', max_length=10),
            preserve_default=False,
        ),
    ]
