# Generated by Django 4.2.5 on 2023-09-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_course_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pho',
            field=models.CharField(default='cj', max_length=20),
            preserve_default=False,
        ),
    ]
