# Generated by Django 4.2.5 on 2023-09-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_facultycoursemapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='aadharno',
            field=models.CharField(default='nsc', max_length=20),
            preserve_default=False,
        ),
    ]
